<?php
/**
 * @file
 * Blocks simple cache.
 */

/**
 * Implements hook_menu().
 */
function blocks_mass_cache_menu() {
  $items = array();

  $items['admin/structure/block/mass-cache'] = array(
    'title' => 'Mass Cache Settings',
    'description' => 'Settings for Blocks Simple Cache',
    'page callback' => 'drupal_get_form',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('blocks_mass_cache_admin_settings_form'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'blocks_mass_cache.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function blocks_mass_cache_help($path, $arg) {
  switch ($path) {
    case 'admin/structure/block/mass-cache':
      return t('Blocks Mass Cache will set global caching for all your blocks.');
  }
}

/**
 * Implements hook_block_info_alter().
 */
function blocks_mass_cache_block_info_alter(&$blocks, $theme, $code_blocks) {
  _blocks_mass_cache_set_cache($blocks);
}

/**
 * Implements hook_context_block_info_alter().
 */
function blocks_mass_cache_context_block_info_alter(&$blocks) {
  _blocks_mass_cache_set_cache($blocks);
}

/**
 * _blocks_mass_cache_set_cache().
 * 
 * Helper function to set cache.
 */
function _blocks_mass_cache_set_cache(&$blocks) {
  // Check if drupal's block caching is enabled.
  if (variable_get('block_cache', FALSE)) {
    // Check if blocks simple cache is enabled.
    if (variable_get('blocks_mass_cache_enabled', FALSE)) {
      // Get list of exceptions.
      $exception_list = variable_get('blocks_mass_cache_exception_list', array());

      // Loop through blocks.
      foreach ($blocks as $module => $block) {
        // Check if block is array (drupal's default).
        if (is_array($block)) {
          foreach ($blocks[$module] as $key => $block_content) {
            $bid = $block_content['module'] . '-' . $block_content['delta'];
            // Check if the block is listed in the exception list.
            if ((!isset($exception_list[$bid]) || (isset($exception_list[$bid])) && $exception_list[$bid] == FALSE)) {
              // Set global caching.
              $blocks[$module][$key]['cache'] = DRUPAL_CACHE_PER_PAGE;
            }
          }
        }
        // Check if block is object (context's module).
        if (is_object($block)) {
          $bid = $block->module . '-' . $block->delta;
          // Check if the block is listed in the exception list.
          if ((!isset($exception_list[$bid]) || (isset($exception_list[$bid])) && $exception_list[$bid] == FALSE)) {
            // Set global caching.
            $blocks[$bid]->cache = DRUPAL_CACHE_PER_PAGE;
          }
        }
      }
    }
  }
}
